# swagger2
swagger2.package: cn.binux.admin.controller

#配置模板想到classpath路径，后面须加上"/"
beetl:
  templates-path: templates/
  config:
      html-tag-flag: true
#配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html

# fastdfs url
fastdfs.base.url: http://192.168.125.132/

# fastdfs storage
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.125.129:22122

