spring:
  application:
    name: admin-dashboard

server:
  port: ${port:8505}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8501/eureka/}
  instance:
    hostname: ${hostname:admin}
    prefer-ip-address: true

